export const LOAD_ARTICLES = "LOAD_ARTICLES"
export const LOAD_EACH_ATTICLE = 'LOAD_EACH_ATTICLE'
export const RECEIVE_ARTICLES_SUCCESS = 'RECEIVE_ATTICLE_SUCCESS'
export const RECEIVE_ARTICLES_FAIL = 'RECEIVE_ATTICLE_FAIL'


